export const PLATFORM_COMMISSION_RATE = 0.25;
export const PLATFORM_COMMISSION_VAT_RATE = 0.19;
export const NET_PROVIDER_SHARE_FACTOR =
  1 - PLATFORM_COMMISSION_RATE * (1 + PLATFORM_COMMISSION_VAT_RATE);
